version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env  # Load environment variables from backend
    ports:
      - "5432:5432"
    expose:
      - 5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-backend
    env_file:
      - ./backend/.env  # Load environment variables from backend
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db
    command: ["./mvnw", "spring-boot:run"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    env_file:
      - ./frontend/.env  # Load environment variables from frontend
    volumes:
      - ./frontend:/frontend  # Mount frontend source code for live updates
      - /frontend/node_modules # Prevent overwriting node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    expose:
      - 3000
    command: ["yarn", "start"]

volumes:
  postgres_data:
