apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: testdocker-backend:latest  # ✅ Make sure this matches your Minikube image
          imagePullPolicy: Never  # ✅ Prevent Kubernetes from pulling from Docker Hub
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config  # Load ConfigMap variables
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_PASSWORD
