apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: testdocker-frontend:latest  # ✅ Make sure this matches your Minikube image
          imagePullPolicy: Never  # ✅ Prevent Kubernetes from pulling from Docker Hub
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: frontend-config  # ✅ Load REACT_APP_BACKEND_URL from ConfigMap
