apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # ✅ Make it accessible from a browser on port 80
      targetPort: 3000  # ✅ React runs on port 3000 inside the pod
  type: LoadBalancer  # ✅ This exposes the service externally
